version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: todo_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
    networks:
      - todo_network

networks:
  todo_network:
    driver: bridge

volumes:
  mongodb_data:
